import argparse
import json
import csv
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Dict, List

import plots

class CubeVisualizer:
    def __init__(self, results_dir: str = "results", style: str = "light"):
        self.results_dir = Path(results_dir)
        self.plot_dir = Path("plots")
        self.plot_dir.mkdir(exist_ok=True)
        
        self.do_export = False
        
        self.method_colors = {
            "lbl": "#d65f4d", "ortega": "#9288d1", 
            "cll": "#47c984", "eg": "#f5a631", "optimal": "#555555"
        }
        self._apply_theme(style)

    def _apply_theme(self, style: str):
        if style == "dark":
            plt.style.use('dark_background')
        else:
            plt.style.use('seaborn-v0_8-whitegrid')
            plt.rcParams.update({
                'axes.grid': True, 'grid.alpha': 0.3, 'grid.linestyle': '--',
                'axes.spines.top': False, 'axes.spines.right': False
            })

    def load_optimal_data(self, method: str, colors: List[str]) -> np.ndarray:
        method_dir = self.results_dir / method.lower()
        color_data_list = []
        for c in colors:
            p = method_dir / f"{c}_data.npy"
            if p.exists(): color_data_list.append(np.load(p))
            
        if not color_data_list:
            raise FileNotFoundError(f"No data for {method}")

        merged_data = color_data_list[0].copy()
        step_names = [n for n in merged_data.dtype.names if n != 'depth']
        n_colors, N = len(color_data_list), len(merged_data)

        totals = np.full((n_colors, N), np.inf)
        for i, data in enumerate(color_data_list):
            valid_mask = data['depth'] >= 0
            total_moves = np.zeros(N)
            for step in step_names:
                total_moves += data[step]
            totals[i, valid_mask] = total_moves[valid_mask]

        best_idx = np.argmin(totals, axis=0)
        best_total = np.min(totals, axis=0)

        for step in step_names:
            stacked = np.vstack([d[step] for d in color_data_list])
            chosen = stacked[best_idx, np.arange(N)]
            chosen[~np.isfinite(best_total)] = -1
            merged_data[step] = chosen

        return merged_data

    def load_random_data(self, label: str) -> np.ndarray:
        file_path = self.results_dir / f"random_{label.lower()}_data.npy"
        if not file_path.exists():
            raise FileNotFoundError(f"Could not find random data at {file_path}")
        return np.load(file_path)

    def get_total_moves(self, data: np.ndarray) -> np.ndarray:
        valid = data['depth'] >= 0
        step_names = [n for n in data.dtype.names if n not in ['depth']]
        return np.sum([data[s][valid].astype(np.int32) for s in step_names], axis=0)

    def save_plot(self, fig, filename: str):
        out_path = self.plot_dir / filename
        fig.savefig(out_path, dpi=300, bbox_inches='tight')
        plt.close(fig)
        print(f"  [+] Saved {filename}")

    def export_csv(self, data_dict: Dict[str, np.ndarray], prefix: str):
        """Exports the raw underlying state-by-state data to CSV."""
        export_dir = self.results_dir / "exports"
        export_dir.mkdir(exist_ok=True)
        
        for label, data in data_dict.items():
            clean_label = "".join(c if c.isalnum() else "_" for c in label.lower())
            out_path = export_dir / f"{prefix}_raw_{clean_label}.csv"
            
            with open(out_path, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(data.dtype.names)
                writer.writerows(data.tolist())
                
            print(f"  [+] Exported raw underlying data to {out_path}")

    def save_computed_csv(self, filename: str, headers: List[str], rows: List[list]):
        """Exports the calculated mathematical data points generated by the plots."""
        if not self.do_export:
            return
            
        export_dir = self.results_dir / "exports"
        export_dir.mkdir(exist_ok=True)
        out_path = export_dir / filename
        
        with open(out_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(headers)
            writer.writerows(rows)
            
        print(f"  [+] Exported computed plot data to {out_path}")


def main():
    parser = argparse.ArgumentParser(description='2x2 Method Deep-Dive Visualizer')
    parser.add_argument('--config', help='Path to JSON config')
    parser.add_argument('--dist-npy', default='pocket2x2_depths_htm_modrot.npy', help='Optimal distances file')
    parser.add_argument('--plots', nargs='+', help='Select: matrix, gap, totals, auf, split, perstep, random')
    parser.add_argument('--force', action='store_true', help='Regenerate existing plots')
    parser.add_argument('--export', action='store_true', help='Export underlying & computed data to CSV')
    args = parser.parse_args()

    viz = CubeVisualizer()
    viz.do_export = args.export
    
    if args.config:
        with open(args.config, 'r') as f:
            config = json.load(f)
            methods_list = config.get('methods', [])
            print(f"Loading Configuration: {config.get('name', 'Method Comparison')}")
    else:
        print("No config. Scanning results/ for all methods...")
        methods_list = [{"method": d.name, "label": d.name.upper()} 
                       for d in viz.results_dir.iterdir() if d.is_dir()]

    optimal_dist = np.load(args.dist_npy) if Path(args.dist_npy).exists() else None

    plot_map = {
        'matrix': (plots.plot_main_comparison_matrix, "method_comparison_matrix.png"),
        'gap': (plots.plot_efficiency_gap_faceted, "efficiency_gap_faceted.png"),
        'totals': (plots.plot_per_method_totals, "method_totals_faceted.png"),
        'auf': (plots.plot_auf_grouped_bars, "auf_comparison.png"),
        'split': (plots.plot_first_vs_remainder_lines, "first_vs_remainder.png"),
        'perstep': (plots.plot_per_step_volume, "per_step_distribution.png"),
        'random': (plots.plot_random_comparison_summary, "random_comparison_summary.png")
    }

    selected_plots = args.plots if args.plots else [k for k in plot_map.keys() if 'random' not in k]

    needs_full_data = any('random' not in p for p in selected_plots)
    needs_random_data = any('random' in p for p in selected_plots)

    full_data_dict = {}
    random_data_dict = {}

    for m in methods_list:
        m_key = m['method'].lower()
        label = m.get('label', m_key.upper())
        colors = m.get('colors', ['W', 'Y', 'G', 'B', 'R', 'O'])
        
        base_color = viz.method_colors.get(m_key, '#777777')
        viz.method_colors[label] = m.get('plot_color', base_color)
        
        if needs_full_data:
            try: full_data_dict[label] = viz.load_optimal_data(m_key, colors)
            except FileNotFoundError: pass

        if needs_random_data:
            try: random_data_dict[label] = viz.load_random_data(label)
            except FileNotFoundError: pass

    if not full_data_dict and not random_data_dict:
        print("No valid data loaded. Exiting.")
        return

    used_full, used_random = False, False

    for p_key in selected_plots:
        if p_key in plot_map:
            func, fname = plot_map[p_key]
            
            is_random_plot = 'random' in p_key
            target_data = random_data_dict if is_random_plot else full_data_dict
            
            if not target_data:
                print(f"  [-] Skipping {p_key}: Required data not found.")
                continue

            if is_random_plot: used_random = True
            else: used_full = True

            if (viz.plot_dir / fname).exists() and not args.force:
                print(f"  [-] Skipping {fname} (already exists, use --force to overwrite)")
                continue
            
            print(f"  [*] Generating {p_key}...")
            if p_key in ['matrix', 'split']:
                func(viz, target_data, optimal_dist)
            else:
                func(viz, target_data)

    if args.export:
        print("\nExporting raw underlying data...")
        if used_full: viz.export_csv(full_data_dict, "full_state")
        if used_random: viz.export_csv(random_data_dict, "random_sample")

if __name__ == "__main__":
    main()