import argparse
import json
import csv
import logging
import sys
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Dict, List, Optional

import plots
import pocket_cube

logging.basicConfig(level=logging.INFO, format="%(message)s", stream=sys.stdout)
logger = logging.getLogger(__name__)

class CubeVisualizer:
    def __init__(self, results_dir: str = "results", style: str = "light", output_subdir: str = ""):
        self.results_dir = Path(results_dir)
        # output_subdir separates one config's outputs from another's when running a whole
        # configs/ directory in one invocation (see main()) -- empty for the single-config /
        # no-config case, which keeps writing straight to plots/ and results/exports/ as before.
        self.plot_dir = Path("plots") / output_subdir if output_subdir else Path("plots")
        self.plot_dir.mkdir(parents=True, exist_ok=True)
        self.export_dir = (self.results_dir / "exports" / output_subdir) if output_subdir else (self.results_dir / "exports")

        self.do_export = False
        
        self.method_colors = {
            "lbl": "#d65f4d", "ortega": "#9288d1", 
            "cll": "#47c984", "eg": "#f5a631", "optimal": "#555555"
        }
        self._apply_theme(style)

    def _apply_theme(self, style: str):
        if style == "dark":
            plt.style.use('dark_background')
        else:
            plt.style.use('seaborn-v0_8-whitegrid')
            plt.rcParams.update({
                'axes.grid': True, 'grid.alpha': 0.3, 'grid.linestyle': '--',
                'axes.spines.top': False, 'axes.spines.right': False
            })

    def load_optimal_data(self, method: str, colors: List[str], cancel_moves: bool = False) -> np.ndarray:
        return pocket_cube.load_optimal_data(self.results_dir, method, colors, cancel_moves=cancel_moves)

    def load_random_data(self, label: str) -> np.ndarray:
        file_path = self.results_dir / f"random_{label.lower()}_data.npy"
        if not file_path.exists():
            raise FileNotFoundError(f"Could not find random data at {file_path}")
        return np.load(file_path)

    def get_total_moves(self, data: np.ndarray) -> np.ndarray:
        valid = data['depth'] >= 0
        # 'reduced_savings' isn't a move count to add -- it's how many fewer moves the solve
        # takes once cancellations are credited (see pocket_cube.load_optimal_data), so it's
        # subtracted, not summed in.
        step_names = [n for n in data.dtype.names if n not in ('depth', 'reduced_savings')]
        total = np.sum([data[s][valid].astype(np.int32) for s in step_names], axis=0)
        if 'reduced_savings' in data.dtype.names:
            total = total - data['reduced_savings'][valid].astype(np.int32)
        return total

    def save_plot(self, fig, filename: str):
        out_path = self.plot_dir / filename
        fig.savefig(out_path, dpi=300, bbox_inches='tight')
        plt.close(fig)
        logger.info(f"  [+] Saved {filename}")

    def export_csv(self, data_dict: Dict[str, np.ndarray], prefix: str):
        """Exports the raw underlying state-by-state data to CSV."""
        self.export_dir.mkdir(parents=True, exist_ok=True)

        for label, data in data_dict.items():
            clean_label = "".join(c if c.isalnum() else "_" for c in label.lower())
            out_path = self.export_dir / f"{prefix}_raw_{clean_label}.csv"

            with open(out_path, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(data.dtype.names)
                writer.writerows(data.tolist())

            logger.info(f"  [+] Exported raw underlying data to {out_path}")

    def save_computed_csv(self, filename: str, headers: List[str], rows: List[list]):
        """Exports the calculated mathematical data points generated by the plots."""
        if not self.do_export:
            return

        self.export_dir.mkdir(parents=True, exist_ok=True)
        out_path = self.export_dir / filename
        
        with open(out_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(headers)
            writer.writerows(rows)

        logger.info(f"  [+] Exported computed plot data to {out_path}")


def run_for_config(config_path: Optional[Path], args: argparse.Namespace, output_subdir: str = "") -> None:
    """Runs the full load -> plot -> export pipeline for one config (or no config, scanning
    results/ for every method). output_subdir keeps one config's plots/exports separate from
    another's when main() is running a whole configs/ directory in one invocation."""
    viz = CubeVisualizer(output_subdir=output_subdir)
    viz.do_export = args.export

    if config_path:
        with open(config_path, 'r') as f:
            config = json.load(f)
            methods_list = config.get('methods', [])
            logger.info(f"Loading Configuration: {config.get('name', 'Method Comparison')}")
    else:
        logger.info("No config. Scanning results/ for all methods...")
        methods_list = [{"method": p.stem, "label": p.stem.upper()}
                       for p in viz.results_dir.glob("*.npz")]

    optimal_dist = np.load(args.dist_npy) if Path(args.dist_npy).exists() else None

    plot_map = {
        'matrix': (plots.plot_main_comparison_matrix, "method_comparison_matrix.png"),
        'gap': (plots.plot_efficiency_gap_faceted, "efficiency_gap_faceted.png"),
        'totals': (plots.plot_per_method_totals, "method_totals_faceted.png"),
        'auf': (plots.plot_auf_grouped_bars, "auf_comparison.png"),
        'split': (plots.plot_first_vs_remainder_lines, "first_vs_remainder.png"),
        'perstep': (plots.plot_per_step_volume, "per_step_distribution.png"),
        'random': (plots.plot_random_comparison_summary, "random_comparison_summary.png")
    }

    selected_plots = args.plots if args.plots else [k for k in plot_map.keys() if 'random' not in k]

    needs_full_data = any('random' not in p for p in selected_plots)
    needs_random_data = any('random' in p for p in selected_plots)

    full_data_dict = {}
    random_data_dict = {}

    for m in methods_list:
        m_key = m['method'].lower()
        label = m.get('label', m_key.upper())
        colors = m.get('colors', ['W', 'Y', 'G', 'B', 'R', 'O'])
        
        base_color = viz.method_colors.get(m_key, '#777777')
        viz.method_colors[label] = m.get('plot_color', base_color)
        
        if needs_full_data:
            try: full_data_dict[label] = viz.load_optimal_data(m_key, colors, cancel_moves=m.get('cancel_moves', False))
            except FileNotFoundError: pass

        if needs_random_data:
            try: random_data_dict[label] = viz.load_random_data(label)
            except FileNotFoundError: pass

    if not full_data_dict and not random_data_dict:
        logger.warning("No valid data loaded. Exiting.")
        return

    used_full, used_random = False, False

    for p_key in selected_plots:
        if p_key in plot_map:
            func, fname = plot_map[p_key]
            
            is_random_plot = 'random' in p_key
            target_data = random_data_dict if is_random_plot else full_data_dict
            
            if not target_data:
                logger.info(f"  [-] Skipping {p_key}: Required data not found.")
                continue

            if is_random_plot: used_random = True
            else: used_full = True

            if (viz.plot_dir / fname).exists() and not args.force:
                logger.info(f"  [-] Skipping {fname} (already exists, use --force to overwrite)")
                continue

            logger.info(f"  [*] Generating {p_key}...")
            if p_key in ['matrix', 'split']:
                func(viz, target_data, optimal_dist)
            else:
                func(viz, target_data)

    if args.export:
        logger.info("\nExporting raw underlying data...")
        if used_full: viz.export_csv(full_data_dict, "full_state")
        if used_random: viz.export_csv(random_data_dict, "random_sample")

def run_comparison(config_a_path: Path, config_b_path: Path, args: argparse.Namespace) -> None:
    """
    Compares two configs method-by-method (e.g. cn_config vs. cn_config_cancellations),
    matched by each entry's `method` field rather than its `label` (labels typically differ
    between the two, e.g. "LBL (CN)" vs. "LBL (CN, Cancellations)"). Both configs must
    ultimately read from the same results/<method>.npz per method for a per-state comparison
    to mean anything -- a state valid in one but not the other would compare a real solve
    against nothing, so states are restricted to those valid under both sides.
    """
    def _load_config(path: Path):
        with open(path, 'r') as f:
            config = json.load(f)
        return config.get('name', path.stem), {m['method'].lower(): m for m in config.get('methods', [])}

    display_name_a, methods_a = _load_config(config_a_path)
    display_name_b, methods_b = _load_config(config_b_path)
    # The JSON 'name' field is meant for prose ("Color Neutral 2x2 Method Comparison (With
    # Cancellations)"), not a repeated chart label -- log it once here, but use the short,
    # always-distinct file stem everywhere it'd otherwise be crammed into a title/legend 4+
    # times over.
    logger.info(f"Comparing '{display_name_a}' ({config_a_path.stem}) vs '{display_name_b}' ({config_b_path.stem})")
    name_a, name_b = config_a_path.stem, config_b_path.stem

    common = [m for m in methods_a if m in methods_b]
    only_a = [m for m in methods_a if m not in methods_b]
    only_b = [m for m in methods_b if m not in methods_a]
    if only_a:
        logger.warning(f"  Skipping (only in {config_a_path.name}): {', '.join(only_a)}")
    if only_b:
        logger.warning(f"  Skipping (only in {config_b_path.name}): {', '.join(only_b)}")
    if not common:
        logger.warning("No methods in common between the two configs. Nothing to compare.")
        return

    output_subdir = f"compare_{config_a_path.stem}_vs_{config_b_path.stem}"
    viz = CubeVisualizer(output_subdir=output_subdir)
    viz.do_export = args.export

    pairs = {}
    for m_key in common:
        entry_a, entry_b = methods_a[m_key], methods_b[m_key]
        label_a = entry_a.get('label', m_key.upper())
        label_b = entry_b.get('label', m_key.upper())

        base_color = viz.method_colors.get(m_key, '#777777')
        viz.method_colors[m_key] = entry_a.get('plot_color', base_color)

        try:
            data_a = viz.load_optimal_data(m_key, entry_a.get('colors', ['W', 'Y', 'G', 'B', 'R', 'O']), cancel_moves=entry_a.get('cancel_moves', False))
            data_b = viz.load_optimal_data(m_key, entry_b.get('colors', ['W', 'Y', 'G', 'B', 'R', 'O']), cancel_moves=entry_b.get('cancel_moves', False))
        except FileNotFoundError as e:
            logger.warning(f"  Skipping {m_key}: {e}")
            continue

        valid = (data_a['depth'] >= 0) & (data_b['depth'] >= 0)
        if not np.any(valid):
            logger.warning(f"  Skipping {m_key}: no states valid under both configs")
            continue

        # get_total_moves restricts to each array's own depth>=0 mask, which won't line up
        # with the other side's positions unless the two masks happen to be identical -- use
        # the shared mask explicitly instead of relying on that coincidence.
        total_a = _total_moves_over(data_a, valid)
        total_b = _total_moves_over(data_b, valid)

        pairs[m_key] = {
            'label_a': label_a, 'label_b': label_b,
            'total_a': total_a, 'total_b': total_b,
            'delta': total_a - total_b,
        }

    if not pairs:
        logger.warning("No comparable data loaded. Exiting.")
        return

    if (viz.plot_dir / "config_comparison.png").exists() and not args.force:
        logger.info("  [-] Skipping config_comparison.png (already exists, use --force to overwrite)")
        return

    plots.plot_config_pair_comparison(viz, pairs, name_a, name_b)

def _total_moves_over(data: np.ndarray, valid: np.ndarray) -> np.ndarray:
    """Like CubeVisualizer.get_total_moves, but restricted to an externally supplied validity
    mask (shared across two datasets being compared state-by-state) instead of the array's
    own depth>=0 mask."""
    step_names = [n for n in data.dtype.names if n not in ('depth', 'reduced_savings')]
    total = np.sum([data[s][valid].astype(np.int32) for s in step_names], axis=0)
    if 'reduced_savings' in data.dtype.names:
        total = total - data['reduced_savings'][valid].astype(np.int32)
    return total

def main():
    parser = argparse.ArgumentParser(description='2x2 Method Deep-Dive Visualizer')
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--config', help='Path to a JSON config, or a directory of them (e.g. configs/) to run every config in one invocation')
    group.add_argument('--compare', nargs=2, metavar=('CONFIG_A', 'CONFIG_B'),
                        help='Compare two configs covering the same methods state-by-state (e.g. --compare configs/cn_config.json configs/cn_config_cancellations.json)')
    parser.add_argument('--dist-npy', default='pocket2x2_depths_htm_modrot.npy', help='Optimal distances file')
    parser.add_argument('--plots', nargs='+', help='Select: matrix, gap, totals, auf, split, perstep, random. Ignored by --compare, which always produces its own comparison plot.')
    parser.add_argument('--force', action='store_true', help='Regenerate existing plots')
    parser.add_argument('--export', action='store_true', help='Export underlying & computed data to CSV')
    args = parser.parse_args()

    if args.compare:
        run_comparison(Path(args.compare[0]), Path(args.compare[1]), args)
        return

    config_path = Path(args.config) if args.config else None

    if config_path and config_path.is_dir():
        config_files = sorted(config_path.glob("*.json"))
        if not config_files:
            logger.warning(f"No .json configs found in {config_path}")
            return
        for cfg in config_files:
            logger.info(f"\n{'='*80}\nCONFIG: {cfg.name}\n{'='*80}")
            run_for_config(cfg, args, output_subdir=cfg.stem)
    else:
        run_for_config(config_path, args)

if __name__ == "__main__":
    main()